version: '3.7'
services:
  jaeger:
    #https://www.jaegertracing.io/docs/1.24/getting-started/
    image: jaegertracing/all-in-one:1.24
    networks:
      - opentracingnetwork
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment: 
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  nginx:
    image: docker.io/emmerson/nginx:jaeger
    networks:
      - opentracingnetwork
    ports:
      - "80:80"
    depends_on:
      - jaeger

  upstream:
    image: emmerson/upstream:mockv2
    networks:
      - opentracingnetwork
    ports:
      - "10003:10003"
      - "10443:10443"
 
networks:
  opentracingnetwork: {}
