apiVersion: v1
kind: Service
metadata:
  labels:
    app: camel-rabbitmq-http
  name: camel-rabbitmq-http
spec:
  ports:
  - name: tcp8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: camel-rabbitmq-http
