apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
  name: jaeger
spec:
  ports:
  - name: udpport-1
    port: 5775
    protocol: UDP
    targetPort: 5775
  - name: udpport-2
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: udpport-3
    port: 6832
    protocol: UDP
    targetPort: 6832
  - name: tcpport-4
    port: 5778
    protocol: TCP
    targetPort: 5778
  - name: tcpport-5
    port: 16686
    protocol: TCP
    targetPort: 16686
  - name: tcpport-6
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app: jaeger