apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: docker.io/emmerson/nginx:jaeger
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/location/
            name: nginx-configs
          - mountPath: /etc/jaeger-nginx-config.json
            name: nginx-configs
            subPath: jaeger-nginx-config.json
      volumes:
        - configMap: 
            name: nginx-configs
          name: nginx-configs

