apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  ports:
  - name: tcpport-1
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: tcpport-2
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: rabbitmq

